#!/bin/sh

usage() {
	echo "usage: sedfiles.sh <pattern> <file> [ <file2> ... ]"
	#echo "usage: sedfiles.sh [-N] <pattern> <file> [ <file2> ... ]"
	echo ""
	echo "Where <pattern> is a sed-compatible regex pattern."
	#echo ""
	#echo "Options:"
	#echo "-N    Dry-run mode, show what will be renamed, but don't actually rename."
}

VERBOSE=1
DRYRUN=1
#TODO: Get the dryrun-variable from the command line flags
#for getopts...

PATTERN="$1"

# Loop over the files, replacing names
for FILENAME in "$@"; do
	echo "${FILENAME}"
	continue

	BACKUPFILE="${FILENAME}.backup"
	rm "${BACKUPFILE}"

	if [ ${VERBOSE} -eq 1 ]; then
		echo "Processing file ${FILENAME}..."
	fi
	if sed -e "${PATTERN}" < "${FILENAME}" > "${BACKUPFILE}"; then
		echo "Error processing ${FILENAME}: not changed."
	else
		mv "${BACKUPFILE}" "${FILENAME}"
	fi
done
